from django.urls import path
from home import views
urlpatterns = [
    path('',views.home,name = 'home'),
    path('shop/<int:id>',views.shop,name = 'shop'),
    path('product/<int:id>',views.product,name = 'product'),
    path('cart',views.cart,name = 'cart'),
    path('add_to_cart/<int:id>',views.add_to_cart,name = 'add_to_cart'),
    path('add_to_cart_from_shop/<int:id>/<int:pid>',views.add_to_cart_from_shop,name = 'add_to_cart_from_shop'),
    path('add_to_cart_from_home/<int:id>/<int:pid>',views.add_to_cart_from_home,name = 'add_to_cart_from_home'),
    path('quantity_plus/<int:id>',views.quantity_plus,name = 'quantity_plus'),
    path('quantity_minus/<int:id>',views.quantity_minus,name = 'quantity_minus'),
    path('remove_item/<int:id>',views.remove_item,name = 'remove_item'),
    path('profile',views.profile,name = 'profile'),
    path('address',views.addr,name = 'address'),
    path('add_address',views.address,name = 'add_address'),
    path('checkout',views.checkout,name = 'checkout'),
    path('place_order',views.placeorder,name = 'placeorde'),
    path('orders',views.orders,name = 'orders'),
    path('orders_delete/<int:id>',views.orders_delete,name = 'orders_delete'),
    path('wishlist',views.wishlist,name = 'wishlist'),
    path('AddToWishlist', views.AddToWishlist, name = "AddToWishlist"),
    path('RemoveFromWish/<int:id>',views.RemoveFromWish, name = "RemoveFromWish"),
    path('AddressEdit/<int:id>',views.AddressEdit,name = 'AddressEdit'),
    path('AddressUpdate/<int:id>',views.AddressUpdate,name = 'AddressUpdate'),
    path('AddressDelete/<int:id>',views.AddressDelete,name = 'AddressDelete'),
    path('EditProfile',views.EditProfile,name = 'EditProfile'),
    path('ProfileUpdate',views.ProfileUpdate,name = 'ProfileUpdate'),
    path('Razorpay',views.Razorpay,name = 'Razorpay'),
    path('EditPassword',views.EditPassword,name = 'EditPassword'),
    path('invoice/<int:id>',views.invoice,name = 'invoice'),
    path('returnItem/<int:id>',views.returnItem,name = 'returnItem'),
    path('coupon_applay/<str:code>',views.coupon_applay,name = 'coupon_applay')
]