# Generated by Django 4.1.2 on 2022-10-26 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_products_description_products_size_products_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.category')),
            ],
        ),
    ]
