# Generated by Django 4.1.2 on 2022-10-29 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_rename_category_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='category',
        ),
        migrations.AddField(
            model_name='sub_category',
            name='Main_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='admins.category'),
            preserve_default=False,
        ),
    ]
