# Generated by Django 4.1.2 on 2022-10-30 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_alter_products_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_files', models.ImageField(upload_to='photo')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.products')),
            ],
        ),
    ]
