# Generated by Django 4.1.2 on 2022-10-31 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_rename_products_products_image_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products_image',
        ),
    ]
