# Generated by Django 4.1.2 on 2022-12-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image1',
            field=models.ImageField(default=0, upload_to='photo'),
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(default=0, upload_to='photo'),
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.ImageField(default=0, upload_to='photo'),
        ),
        migrations.AddField(
            model_name='products',
            name='image4',
            field=models.ImageField(default=0, upload_to='photo'),
        ),
    ]
