# Generated by Django 4.1.2 on 2023-06-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0018_products_image1_products_image2_products_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(default=0, null=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(default=0, null=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image4',
            field=models.ImageField(default=0, null=True, upload_to='photo'),
        ),
    ]
