# Generated by Django 4.1.2 on 2022-11-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_order_status_orderhistory_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order'),
        ),
    ]
