# Generated by Django 4.1.2 on 2022-11-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_orderhistory_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='order',
        ),
    ]
