# Generated by Django 4.1.2 on 2022-11-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_order_status_orderhistory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='discounted_amnt',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
