# Generated by Django 4.1.2 on 2023-06-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_customuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
